export const BUSINESS_INFO = {
  name: "SP Financial Services",
  tagline: "Secure Today. Assured Tomorrow.",
  motto: "A Goal Without a Plan is Just a Wish",
  subTagline: "Protecting Lives... Securing Futures...",
  founders: [
    {
      name: "Sachin Pandit",
      role: "Founder & Financial Advisor",
      phone: "+919870577706",
      phoneDisplay: "+91 98705 77706",
      whatsapp: "https://wa.me/919870577706",
      achievements: "MDRT – USA (Last 6 Years)",
    },
    {
      name: "Rakhi Pandit",
      role: "Co-Founder & Financial Advisor",
      phone: "+919699788445",
      phoneDisplay: "+91 96997 88445",
      whatsapp: "https://wa.me/919699788445",
    },
  ],
  contact: {
    primaryPhone: "+919870577706",
    primaryPhoneDisplay: "+91 98705 77706",
    whatsapp: "https://wa.me/919870577706",
    secondaryPhone: "+919699788445",
    secondaryPhoneDisplay: "+91 96997 88445",
    email: "sachinpandit1714@gmail.com",
    address: "201, 202, 2nd Floor, Sayba Palace, Nr. New Post Office, Kurla (W), Mumbai - 400070",
    fullAddressDetails: "C/24, 201/202, 2nd Floor, Sayba Palace, Wadia Marg, Near New Post Office, Kurla (W), Mumbai - 400070",
    googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.835154378775!2d72.87532297596593!3d19.070966982132338!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c8913b784a51%3A0xe5a36e8494cb45f8!2sSayba%20Palace%2C%20Wadia%20Marg%2C%20Kurla%20West%2C%20Kurla%2C%20Mumbai%2C%20Maharashtra%20400070!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
    instagram: "https://www.instagram.com/sp_financial_services/",
    instagramHandle: "@sp_financial_services",
    youtube: "https://youtube.com/@sp_financial_services",
    youtubeHandle: "@SP_Financial_Services",
    youtubeShort: "https://youtube.com/shorts/OuuJjjAM-sE",
    instagramReel: "https://www.instagram.com/reel/C4df3gTSEbx/",
  },
  stats: [
    { label: "Happy Clients", value: 1500, suffix: "+", description: "Trusted families & businesses across India" },
    { label: "Years Experience", value: 16, suffix: "+", description: "Dedicated advisory & wealth planning" },
    { label: "MDRT – USA Award", value: 6, suffix: " Years", description: "Consecutive international excellence" },
    { label: "Trophies & Awards", value: 65, suffix: "+", description: "Accolades from LIC & financial bodies" },
  ],
  insurancePartners: [
    {
      id: "lic",
      name: "Life Insurance Corporation (LIC)",
      badge: "LIC OF INDIA · MDRT",
      tagline: "India's largest & most trusted life insurer",
      color: "from-amber-600/20 to-amber-900/20",
      accent: "#D4AF37",
      logo: "/images/partners/lic.png",
      coverageTypes: ["Term Life", "Endowment Plans", "Retirement Pensions", "Child Future"],
    },
    {
      id: "hdfc-ergo",
      name: "HDFC ERGO General Insurance",
      badge: "HDFC ERGO",
      tagline: "Comprehensive general, motor & health coverage",
      color: "from-red-600/20 to-red-900/20",
      accent: "#E06B2C",
      logo: "/images/partners/hdfc-ergo.png",
      coverageTypes: ["Motor Insurance", "Health Suraksha", "Home Shield", "Travel Protection"],
    },
    {
      id: "star-health",
      name: "Star Health & Allied Insurance",
      badge: "STAR HEALTH INSURANCE",
      tagline: "India's premier standalone health insurance specialist",
      color: "from-blue-600/20 to-blue-900/20",
      accent: "#2E9BD6",
      logo: "/images/partners/star-health.png",
      coverageTypes: ["Family Mediclaim", "Senior Citizen", "Critical Illness", "Super Surplus"],
    },
    {
      id: "nj-wealth",
      name: "NJ Mutual Fund & E-Wealth",
      badge: "NJ MUTUAL FUND",
      tagline: "Smart wealth creation, SIPs & portfolio management",
      color: "from-emerald-600/20 to-emerald-900/20",
      accent: "#1E8F5F",
      logo: "/images/partners/nj-wealth.png",
      coverageTypes: ["SIPs & Mutual Funds", "Equity Portfolios", "Debt & Liquid Funds", "Tax-saving ELSS"],
    },
  ],
};

export const CORE_SERVICES = [
  {
    id: "retirement-solutions",
    title: "Retirement Solutions",
    category: "Wealth & Pension",
    shortDesc: "Guaranteed lifelong regular income and pension plans designed for a carefree, dignified post-work life.",
    iconColor: "text-amber-500 bg-amber-500/10 border-amber-500/20",
    features: ["Guaranteed annuity for lifetime", "Inflation-adjusted pensions", "Tax-free maturity corpus", "Spouse pension continuity"],
  },
  {
    id: "wealth-creation",
    title: "Wealth Creation Planning",
    category: "Investment Advisory",
    shortDesc: "Strategic disciplined investments across mutual funds, SIPs, and high-yield plans to multiply long-term capital.",
    iconColor: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
    features: ["Goal-based SIPs", "Compounding advantage", "Active risk management", "Portfolio rebalancing"],
  },
  {
    id: "education-plans",
    title: "Child Education & Marriage Plans",
    category: "Family Future",
    shortDesc: "Ensure adequate financial backing for your children's higher education and marriage milestones without taking loans.",
    iconColor: "text-blue-500 bg-blue-500/10 border-blue-500/20",
    features: ["Milestone payout scheduling", "Premium waiver benefit on parent", "Inflation-hedged fund growth", "Guaranteed loan-free education"],
  },
  {
    id: "virtual-property",
    title: "Virtual Property Creation",
    category: "Asset Building",
    shortDesc: "Build an immediate liquid estate and high-value legacy asset for your family with minimal initial capital outlays.",
    iconColor: "text-cyan-500 bg-cyan-500/10 border-cyan-500/20",
    features: ["Instant estate creation", "Zero maintenance or property taxes", "Dispute-free smooth succession", "High liquidity on demand"],
  },
  {
    id: "family-protection",
    title: "Family Financial Protection",
    category: "Comprehensive Insurance",
    shortDesc: "Complete shield against unforeseen medical emergencies, disability, or loss of earning member through top-tier covers.",
    iconColor: "text-rose-500 bg-rose-500/10 border-rose-500/20",
    features: ["High sum assured term covers", "Cashless hospitalization network", "Personal accident & critical illness", "Family floater mediclaim"],
  },
  {
    id: "tax-free-asset",
    title: "Tax-Free Asset & Regular Income",
    category: "Tax Planning",
    shortDesc: "Structure your wealth into government-compliant instruments providing 100% tax-free regular earnings under Sec 10(10D).",
    iconColor: "text-indigo-500 bg-indigo-500/10 border-indigo-500/20",
    features: ["Tax-exempt maturity under 10(10D)", "Section 80C deductions", "Zero volatility guaranteed return", "Annual or monthly cash flows"],
  },
];

export const ALL_COVERAGE_TYPES = [
  { name: "Life Insurance", category: "Core Life" },
  { name: "Travel Insurance", category: "General" },
  { name: "Motor Insurance", category: "General" },
  { name: "Workmen's Compensation", category: "Corporate" },
  { name: "Marine Insurance", category: "Commercial" },
  { name: "Fire Insurance", category: "Property" },
  { name: "Mediclaim Insurance", category: "Health" },
  { name: "Group Mediclaim", category: "Corporate" },
  { name: "Personal Accident", category: "Health" },
  { name: "Corporate Insurance", category: "Commercial" },
  { name: "Keyman Insurance", category: "Corporate" },
  { name: "Child Education Plans", category: "Future" },
  { name: "Retirement & Pension", category: "Life" },
  { name: "SIP & Mutual Funds", category: "Wealth" },
];

export const ASSET_ALLOCATION_TIERS = [
  {
    id: "safe",
    title: "Safe Portfolio",
    returnRange: "5% – 6%",
    returnLabel: "Guaranteed & Tax-Free",
    riskLevel: "Zero / Capital Protected",
    riskMeterWidth: "20%",
    riskColor: "bg-emerald-500",
    taxStatus: "100% Tax-Free (Sec 10(10D))",
    capitalProtection: "100% Sovereign / Insurer Backed",
    description: "Ideal for conservative investors, emergency reserve allocation, and guaranteed milestone goals where capital security is paramount.",
    instruments: ["LIC Guaranteed Plans", "Government Backed Securities", "Fixed Return Annuities", "Sovereign Bonds"],
    keyBenefit: "Zero market volatility, reliable assured payouts, and full tax exemption.",
  },
  {
    id: "medium",
    title: "Medium Risk Portfolio",
    returnRange: "10% – 12%",
    returnLabel: "Balanced Growth",
    riskLevel: "Moderate / Partial Protection",
    riskMeterWidth: "55%",
    riskColor: "bg-amber-500",
    taxStatus: "Tax-Free or Concessional LTCG",
    capitalProtection: "Partial Capital Protection Structure",
    description: "Balanced approach combining stable debt instruments with high-growth equity funds for compounding returns beating inflation comfortably.",
    instruments: ["Hybrid Balanced Advantage Funds", "Multi-Asset Allocation Funds", "Large-Cap Index Funds", "Corporate Debt SIPs"],
    keyBenefit: "Strong inflation hedge, moderate downside buffer, and balanced wealth accumulation.",
  },
  {
    id: "risk",
    title: "Risk Portfolio",
    returnRange: "15% – 18%",
    returnLabel: "High Growth Potential",
    riskLevel: "High / Market Linked",
    riskMeterWidth: "90%",
    riskColor: "bg-rose-500",
    taxStatus: "Subject to Capital Gains Tax",
    capitalProtection: "No Capital Guarantee (Market Linked)",
    description: "High-growth equity mutual funds and small/mid-cap funds engineered for aggressive long-term wealth multiplication over 7+ years.",
    instruments: ["Mid & Small Cap Mutual Funds", "Flexi-Cap Equity Portfolios", "Thematic & Sectoral Funds", "Global Equity Diversification"],
    keyBenefit: "Maximum compounding velocity for long horizons with risk appetite.",
  },
];

export const TESTIMONIALS_DATA = [
  {
    id: "raaj-shaandilyaa",
    name: "Mr. Raaj Shaandilyaa",
    role: "Director, Bollywood Movie \"Dream Girl\"",
    image: "/images/testimonials/raaj-shaandilyaa.png",
    rating: 5,
    quote:
      "Sachin Pandit took the time to deeply analyze our family's insurance portfolio. He optimized our policies, significantly enhanced our protection, and reduced unnecessary costs. His integrity, work ethic, and sincere commitment make him one of the finest financial advisors in the industry.",
  },
  {
    id: "mahesh-shirodkar",
    name: "Mr. Mahesh Shirodkar",
    role: "Director, Mailit",
    image: "/images/testimonials/mahesh-shirodkar.png",
    rating: 5,
    quote:
      "After searching for comprehensive life insurance coverage for a long time, Sachin Pandit worked tirelessly to find the exact plan matching my criteria. His patience and prompt follow-up were exceptional. I could not be more grateful for his outstanding guidance.",
  },
  {
    id: "aarambh-singh",
    name: "Mr. Aarambh Singh",
    role: "Assistant Director, Bollywood Movie \"Badlapur\"",
    image: "/images/testimonials/aarambh-singh.png",
    rating: 5,
    quote:
      "In a world where financial services often feel impersonal, Sachin Pandit stands out with his warm personal touch and exceptional customer care. He has always provided prompt, objective, and proactive advice for all our family's insurance needs.",
  },
  {
    id: "sonam-almeda",
    name: "Ms. Sonam Almeda",
    role: "HR Head, J.P. Morgan",
    image: "/images/testimonials/sonam-almeda.png",
    rating: 5,
    quote:
      "Thank you Sachin and team for your patient guidance. I had numerous questions regarding complex policy options, and you walked me through every detail transparently. The entire onboarding was seamless, and the professionalism of SP Financial Services is truly remarkable.",
  },
];

export const AWARDS_TIMELINE = [
  {
    year: "Last 6 Years",
    title: "Prestigious MDRT – USA Award Winner",
    organization: "Million Dollar Round Table (MDRT USA)",
    description: "Premier international association for financial professionals, representing the top tier of insurance and financial advisors worldwide.",
    highlight: true,
    trophyImage: "/images/awards/trophy-mdrt.png",
  },
  {
    year: "Last 6 Years",
    title: "Prestigious Corporate Trophy",
    organization: "Life Insurance Corporation of India (LIC)",
    description: "Recognized consecutively for highest corporate business volume, exemplary ethical advisory, and client retention standards.",
    highlight: true,
    trophyImage: "/images/awards/trophy-lic.png",
  },
  {
    year: "Last 3 Years",
    title: "Prestigious Champions Trophy",
    organization: "Life Insurance Corporation of India (LIC)",
    description: "Awarded for exceptional service excellence and leadership in comprehensive insurance solutions.",
    highlight: false,
  },
  {
    year: "2019",
    title: "Double Shatakveer Award",
    organization: "Life Insurance Corporation of India (LIC)",
    description: "Prestigious honor for insuring over 200 lives in a single financial year with flawless advisory.",
    highlight: false,
  },
  {
    year: "2018",
    title: "Shatakveer Award",
    organization: "Life Insurance Corporation of India (LIC)",
    description: "Recognized for surpassing the 100-policy milestone with superior client satisfaction.",
    highlight: false,
  },
  {
    year: "Overall",
    title: "65+ Trophies & State Accolades",
    organization: "LIC, NJ Wealth & Industry Councils",
    description: "Comprehensive array of awards honoring 16+ years of honest client-first advisory in Mumbai.",
    highlight: false,
  },
];

export const AWARD_GALLERY_PHOTOS = [
  {
    year: "2018",
    title: "LIC Shatakveer Felicitation Ceremony",
    src: "/images/awards/award-2018.png",
    description: "Sachin Pandit receiving the prestigious Shatakveer recognition from LIC leadership.",
  },
  {
    year: "2019",
    title: "Double Shatakveer Gala Celebration",
    src: "/images/awards/award-2019.png",
    description: "Sachin & Rakhi Pandit felicitated with the Double Shatakveer trophy at the grand Mumbai convention.",
  },
  {
    year: "2020",
    title: "Corporate Excellence Award Felicitation",
    src: "/images/awards/award-2020.png",
    description: "Recognized by LIC senior division executives for resilience and client commitment.",
  },
  {
    year: "2021",
    title: "MDRT Qualifiers Mumbai Division Meet",
    src: "/images/awards/award-2021.png",
    description: "Grand honors presented to Sachin Pandit at the MDRT Qualifiers Mumbai Division gathering.",
  },
  {
    year: "2022",
    title: "TOT / COT / MDRT Convention",
    src: "/images/awards/award-2022.png",
    description: "Sachin Pandit recognized at the prestigious TOT / COT / MDRT Convention, Mumbai Division-II.",
  },
  {
    year: "2023",
    title: "LIC Grand Convention Stage Honors",
    src: "/images/awards/award-2023.png",
    description: "Sachin & Rakhi Pandit honored on stage at the LIC Grand Annual Convention celebrating 6 consecutive years of MDRT excellence.",
  },
];

export const WHY_CHOOSE_US_POINTS = [
  {
    title: "Reliable Solutions",
    desc: "Custom-tailored financial plans aligned directly with your personal goals and risk tolerance.",
    icon: "ShieldCheck",
    color: "bg-blue-50 text-blue-700",
  },
  {
    title: "Expert Advice",
    desc: "16+ years of specialized market experience and MDRT USA-certified advisory standards.",
    icon: "Award",
    color: "bg-amber-50 text-amber-700",
  },
  {
    title: "Honest Service",
    desc: "100% transparent counsel with zero hidden charges, conflicts of interest, or unnecessary push.",
    icon: "Handshake",
    color: "bg-emerald-50 text-emerald-700",
  },
  {
    title: "Quick Claim Support",
    desc: "Dedicated personal assistance during critical claim settlement times when you need it most.",
    icon: "ClockCheck",
    color: "bg-cyan-50 text-cyan-700",
  },
];

export const FINANCIAL_REELS_DATA = [
  {
    id: "lic-pension-1lakh",
    title: "₹1,00,000 Zindagi Bhar... (LIC Pension Plan)",
    topic: "Retirement Planning",
    category: "retirement",
    badge: "Lifelong Pension",
    image: "/images/reels/reel-lic-pension-1lakh.jpg",
    description: "Guaranteed lifelong regular monthly income for a secure and dignified retirement.",
    speakers: "Sachin & Rakhi Pandit",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "lic-amritbaal",
    title: "Amritbaal Policy: Child Higher Education",
    topic: "Child Planning",
    category: "child",
    badge: "Education Shield",
    image: "/images/reels/reel-lic-amritbaal.jpg",
    description: "Structure a dedicated higher education fund so your child never has to rely on education loans.",
    speakers: "Sachin Pandit",
    tagColor: "bg-blue-500/20 text-blue-300 border-blue-500/40",
  },
  {
    id: "fd-vs-swp",
    title: "FD vs SWP (Systematic Withdrawal Plan)",
    topic: "Smart Income",
    category: "retirement",
    badge: "Better than FDs",
    image: "/images/reels/reel-fd-vs-swp.jpg",
    description: "Compare low bank FD interest against tax-efficient monthly income via Mutual Fund SWPs.",
    speakers: "Sachin Pandit",
    tagColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
  },
  {
    id: "topup-sip",
    title: "Top-Up SIP: Paisa Double (2x / 4x)",
    topic: "Wealth Compounding",
    category: "sip",
    badge: "SIP Strategy",
    image: "/images/reels/reel-topup-sip.jpg",
    description: "Learn how step-up SIPs multiply wealth significantly faster than static monthly investments.",
    speakers: "Sachin Pandit",
    tagColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
  },
  {
    id: "mutual-funds-5-reasons",
    title: "5 Reasons to Invest in Mutual Funds",
    topic: "Mutual Funds",
    category: "sip",
    badge: "Smart Investing",
    image: "/images/reels/reel-mutual-funds-5-reasons.jpg",
    description: "Key principles why mutual funds beat inflation and generate superior long-term returns.",
    speakers: "Sachin & Rakhi Pandit",
    tagColor: "bg-gold-400/20 text-gold-300 border-gold-400/40",
  },
  {
    id: "first-salary",
    title: "1st Salary: Aap Kya Loge? (Asset vs Expense)",
    topic: "Youth Financial Habits",
    category: "advisory",
    badge: "Early Discipline",
    image: "/images/reels/reel-first-salary.jpg",
    description: "Why investing your first salary into compounding assets creates lifelong financial freedom.",
    speakers: "Sachin Pandit",
    tagColor: "bg-teal-500/20 text-teal-300 border-teal-500/40",
  },
  {
    id: "mediclaim-warning",
    title: "Mediclaim Policy Nahi Thi!",
    topic: "Health Protection",
    category: "health",
    badge: "Emergency Shield",
    image: "/images/reels/reel-mediclaim-warning.jpg",
    description: "Why medical emergencies without insurance wipe out years of hard-earned family savings.",
    speakers: "Sachin Pandit",
    tagColor: "bg-rose-500/20 text-rose-300 border-rose-500/40",
  },
  {
    id: "mediclaim-youth",
    title: "Mediclaim Policy for 18–40 Years",
    topic: "Family Health",
    category: "health",
    badge: "Youth Advantage",
    image: "/images/reels/reel-mediclaim-youth.jpg",
    description: "Why taking health insurance early locks in the lowest premiums and widest coverage.",
    speakers: "Sachin & Rakhi Pandit",
    tagColor: "bg-blue-500/20 text-blue-300 border-blue-500/40",
  },
  {
    id: "why-choose-professional",
    title: "Why Choose a Professional Advisor?",
    topic: "Expert Guidance",
    category: "advisory",
    badge: "MDRT Standards",
    image: "/images/reels/reel-why-choose-professional.jpg",
    description: "The difference between DIY financial mistakes and certified professional MDRT guidance.",
    speakers: "Sachin Pandit",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
];


